- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: LAB2Azure
      allocation_method: Static
      name: LAB2-LinuxPublicIP
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: LAB2Azure
      name: LAB2-LinuxNSG
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: LAB2Azure
      name: LAB2-LinuxNIC
      virtual_network: LAB2-VNET
      subnet: ProtectedSubnet
      public_ip_name: LAB2-LinuxPublicIP
      security_group: LAB2-LinuxNSG
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: LAB2Azure
      name: LAB2-LinuxVM
      vm_size: Standard_B2s
      managed_disk_type: Standard_LRS
      admin_username: linuxuser
      admin_password: Fortipassword123
      ssh_password_enabled: true
      network_interfaces: LAB2-LinuxNIC
      image:
        offer: 0001-com-ubuntu-server-jammy
        publisher: Canonical
        sku: 22_04-lts-gen2
        version: latest