---
- hosts: localhost
  connection: local
  tasks:
    - name: Create_virtual_hub_connection
      azure_rm_virtualhubconnection:
        resource_group: LAB2AZure
        vhub_name: LAB2-HUB-centralus
        name: Myconnection
        enable_internet_security: false
        allow_remote_vnet_to_use_hub_vnet_gateways: true
        allow_hub_to_remote_vnet_transit: true
        remote_virtual_network:
          id: /subscriptions/21399b64-cedc-49cc-a00c-017ec42492ac/resourceGroups/LAB2AZure/providers/Microsoft.Network/virtualNetworks/LAB2-VNET
      #id: LAB2-VNET
    #routing_configuration:
    #  propagated_route_tables:
        #labels:
        #  - labels1
        #  - labels3
     #   ids:
      #    - id: LAB2-RouteTable-ProtectedASubnet
         # - id: /subscriptions/21399b64-cedc-49cc-a00c-017ec42492ac/resourceGroups/LAB2AZure/providers/Microsoft.Network/virtualHubs/LAB2-HUB-centralus/hubRouteTables/testtable
      #vnet_routes:
      #  static_routes:
      #    - name: route1
      #      address_prefixes:
      #        - 10.1.0.0/16
      #        - 10.2.0.0/16
      #      next_hop_ip_address: 10.0.0.68
      #    - name: route2
      #      address_prefixes:
      #        - 10.4.0.0/16
      #      next_hop_ip_address: 10.0.0.65
